"""
TJ_Vector - ComfyUI Custom Nodes
Line art to vector conversion nodes
"""

from .line_region_detector import NODE_CLASS_MAPPINGS as LINE_NODES, NODE_DISPLAY_NAME_MAPPINGS as LINE_NAMES
from .centerline_to_svg import NODE_CLASS_MAPPINGS as SVG_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_NAMES
from .svg_file_saver import NODE_CLASS_MAPPINGS as SAVER_NODES, NODE_DISPLAY_NAME_MAPPINGS as SAVER_NAMES
from .mask_cleanup import NODE_CLASS_MAPPINGS as CLEANUP_NODES, NODE_DISPLAY_NAME_MAPPINGS as CLEANUP_NAMES
from .svg_path_cleanup import NODE_CLASS_MAPPINGS as SVG_CLEANUP_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_CLEANUP_NAMES
from .svg_to_raster import NODE_CLASS_MAPPINGS as SVG_TO_IMAGE_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_TO_IMAGE_NAMES
from .python_info import NODE_CLASS_MAPPINGS as PY_INFO_NODES, NODE_DISPLAY_NAME_MAPPINGS as PY_INFO_NAMES
from .svg_group_layout import NODE_CLASS_MAPPINGS as SVG_GROUP_LAYOUT_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_GROUP_LAYOUT_NAMES
from .svg_style_editor import NODE_CLASS_MAPPINGS as SVG_STYLE_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_STYLE_NAMES
from .svg_style_editor_simple import NODE_CLASS_MAPPINGS as SVG_STYLE_SIMPLE_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_STYLE_SIMPLE_NAMES
from .svg_reorder import NODE_CLASS_MAPPINGS as SVG_REORDER_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_REORDER_NAMES
from .svg_visibility import NODE_CLASS_MAPPINGS as SVG_VISIBILITY_NODES, NODE_DISPLAY_NAME_MAPPINGS as SVG_VISIBILITY_NAMES

# Combine all node mappings
NODE_CLASS_MAPPINGS = {
    **LINE_NODES,
    **SVG_NODES,
    **SAVER_NODES,
    **CLEANUP_NODES,
    **SVG_CLEANUP_NODES,
    **SVG_TO_IMAGE_NODES,
    **PY_INFO_NODES,
    **SVG_GROUP_LAYOUT_NODES,
    **SVG_STYLE_NODES,
    **SVG_STYLE_SIMPLE_NODES,
    **SVG_REORDER_NODES,
    **SVG_VISIBILITY_NODES
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **LINE_NAMES,
    **SVG_NAMES,
    **SAVER_NAMES,
    **CLEANUP_NAMES,
    **SVG_CLEANUP_NAMES,
    **SVG_TO_IMAGE_NAMES,
    **PY_INFO_NAMES,
    **SVG_GROUP_LAYOUT_NAMES,
    **SVG_STYLE_NAMES,
    **SVG_STYLE_SIMPLE_NAMES,
    **SVG_REORDER_NAMES,
    **SVG_VISIBILITY_NAMES
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
